//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFZ.Communication
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://schemas.datacontract.org/2004/07/DFZ.Communication")]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CheckpointsField;
        
        private string ClientApplicationField;
        
        private string ClientMachineNameField;
        
        private System.Guid CorrelationTokenField;
        
        private DFZ.Communication.ErrorMode ErrorModeField;
        
        private System.Nullable<System.DateTime> LastCheckpointSetField;
        
        private DFZ.Communication.MessageType MessageTypeField;
        
        private string NameField;
        
        private DFZ.Communication.Parameter[] ParametersField;
        
        private DFZ.Communication.Priority PriorityField;
        
        private System.DateTime TimeToDeliverField;
        
        private string UserField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Checkpoints
        {
            get
            {
                return this.CheckpointsField;
            }
            set
            {
                this.CheckpointsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientApplication
        {
            get
            {
                return this.ClientApplicationField;
            }
            set
            {
                this.ClientApplicationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientMachineName
        {
            get
            {
                return this.ClientMachineNameField;
            }
            set
            {
                this.ClientMachineNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CorrelationToken
        {
            get
            {
                return this.CorrelationTokenField;
            }
            set
            {
                this.CorrelationTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DFZ.Communication.ErrorMode ErrorMode
        {
            get
            {
                return this.ErrorModeField;
            }
            set
            {
                this.ErrorModeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastCheckpointSet
        {
            get
            {
                return this.LastCheckpointSetField;
            }
            set
            {
                this.LastCheckpointSetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DFZ.Communication.MessageType MessageType
        {
            get
            {
                return this.MessageTypeField;
            }
            set
            {
                this.MessageTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DFZ.Communication.Parameter[] Parameters
        {
            get
            {
                return this.ParametersField;
            }
            set
            {
                this.ParametersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DFZ.Communication.Priority Priority
        {
            get
            {
                return this.PriorityField;
            }
            set
            {
                this.PriorityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeToDeliver
        {
            get
            {
                return this.TimeToDeliverField;
            }
            set
            {
                this.TimeToDeliverField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorMode", Namespace="http://schemas.datacontract.org/2004/07/DFZ.Communication")]
    public enum ErrorMode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NeverThrow = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ThrowOnError = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ThrowOnErrorAndWarning = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageType", Namespace="http://schemas.datacontract.org/2004/07/DFZ.Communication")]
    public enum MessageType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RequestResponse = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FireForget = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parameter", Namespace="http://schemas.datacontract.org/2004/07/DFZ.Communication")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DFZ.Communication.Request))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DFZ.Communication.ErrorMode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DFZ.Communication.MessageType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DFZ.Communication.Parameter[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DFZ.Communication.ParameterDirection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DFZ.Communication.Priority))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DFZ.Communication.Response))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DFZ.Communication.DataCommunicationServiceException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DFZ.Communication.ResponseMessage[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DFZ.Communication.ResponseMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DFZ.Communication.ResponseStatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DFZ.Communication.Response[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DFZ.Communication.WCFServiceFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DFZ.Common.IdentifiableException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Exception))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.KeyValuePair<string, string>[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.KeyValuePair<string, string>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    public partial class Parameter : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private DFZ.Communication.ParameterDirection DirectionField;
        
        private string NameField;
        
        private int OrderField;
        
        private object ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DFZ.Communication.ParameterDirection Direction
        {
            get
            {
                return this.DirectionField;
            }
            set
            {
                this.DirectionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Order
        {
            get
            {
                return this.OrderField;
            }
            set
            {
                this.OrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Priority", Namespace="http://schemas.datacontract.org/2004/07/DFZ.Communication")]
    public enum Priority : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Normal = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AboveNormal = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        High = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Highest = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Low = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Lowest = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VeryHigh = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VeryLow = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParameterDirection", Namespace="http://schemas.datacontract.org/2004/07/DFZ.Communication")]
    public enum ParameterDirection : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        In = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Out = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/DFZ.Communication")]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CheckpointsField;
        
        private DFZ.Communication.DataCommunicationServiceException FaultField;
        
        private System.Nullable<System.DateTime> LastCheckpointSetField;
        
        private DFZ.Communication.ResponseMessage[] MessagesField;
        
        private DFZ.Communication.Parameter[] OutParametersField;
        
        private DFZ.Communication.Request RequestField;
        
        private DFZ.Communication.ResponseStatus ResponseStatusField;
        
        private string ResponseTypeField;
        
        private string[] ResultField;
        
        private DFZ.Communication.Response[] SubResponsesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Checkpoints
        {
            get
            {
                return this.CheckpointsField;
            }
            set
            {
                this.CheckpointsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DFZ.Communication.DataCommunicationServiceException Fault
        {
            get
            {
                return this.FaultField;
            }
            set
            {
                this.FaultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastCheckpointSet
        {
            get
            {
                return this.LastCheckpointSetField;
            }
            set
            {
                this.LastCheckpointSetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DFZ.Communication.ResponseMessage[] Messages
        {
            get
            {
                return this.MessagesField;
            }
            set
            {
                this.MessagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DFZ.Communication.Parameter[] OutParameters
        {
            get
            {
                return this.OutParametersField;
            }
            set
            {
                this.OutParametersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DFZ.Communication.Request Request
        {
            get
            {
                return this.RequestField;
            }
            set
            {
                this.RequestField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DFZ.Communication.ResponseStatus ResponseStatus
        {
            get
            {
                return this.ResponseStatusField;
            }
            set
            {
                this.ResponseStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseType
        {
            get
            {
                return this.ResponseTypeField;
            }
            set
            {
                this.ResponseTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DFZ.Communication.Response[] SubResponses
        {
            get
            {
                return this.SubResponsesField;
            }
            set
            {
                this.SubResponsesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.SerializableAttribute()]
    public partial class DataCommunicationServiceException : DFZ.Common.IdentifiableException
    {
        
        public DataCommunicationServiceException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context)
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseMessage", Namespace="http://schemas.datacontract.org/2004/07/DFZ.Communication")]
    public partial class ResponseMessage : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.KeyValuePair<string, string>[] Valuesk__BackingFieldField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Values>k__BackingField", IsRequired=true)]
        public System.Collections.Generic.KeyValuePair<string, string>[] Valuesk__BackingField
        {
            get
            {
                return this.Valuesk__BackingFieldField;
            }
            set
            {
                this.Valuesk__BackingFieldField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseStatus", Namespace="http://schemas.datacontract.org/2004/07/DFZ.Communication")]
    public enum ResponseStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotDetermined = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ok = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotDelivered = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WCFServiceFault", Namespace="http://schemas.datacontract.org/2004/07/DFZ.Communication")]
    public partial class WCFServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FaultMessageField;
        
        private System.Guid IdentifierField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultMessage
        {
            get
            {
                return this.FaultMessageField;
            }
            set
            {
                this.FaultMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Identifier
        {
            get
            {
                return this.IdentifierField;
            }
            set
            {
                this.IdentifierField = value;
            }
        }
    }
}
namespace DFZ.Common
{
    using System;
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DFZ.Communication.DataCommunicationServiceException))]
    public partial class IdentifiableException : System.Exception
    {
        
        public IdentifiableException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context)
        {
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IDataService")]
public interface IDataService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Execute", ReplyAction="http://tempuri.org/IDataService/ExecuteResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(DFZ.Communication.WCFServiceFault), Action="http://tempuri.org/IDataService/ExecuteWCFServiceFaultFault", Name="WCFServiceFault", Namespace="http://schemas.datacontract.org/2004/07/DFZ.Communication")]
    DFZ.Communication.Response Execute(DFZ.Communication.Request request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Execute", ReplyAction="http://tempuri.org/IDataService/ExecuteResponse")]
    System.Threading.Tasks.Task<DFZ.Communication.Response> ExecuteAsync(DFZ.Communication.Request request);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IDataServiceChannel : IDataService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DataServiceClient : System.ServiceModel.ClientBase<IDataService>, IDataService
{
    
    public DataServiceClient()
    {
    }
    
    public DataServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public DFZ.Communication.Response Execute(DFZ.Communication.Request request)
    {
        return base.Channel.Execute(request);
    }
    
    public System.Threading.Tasks.Task<DFZ.Communication.Response> ExecuteAsync(DFZ.Communication.Request request)
    {
        return base.Channel.ExecuteAsync(request);
    }
}
